#config_version=6

config:
  - machine.yaml
  - game.yaml
  - players.yaml
  - widget_styles.yaml

hardware:
  platform: virtual

displays:
  window:
    width: 800
    height: 480

machine:
  balls_installed: 1

modes:
  - attract
  - base

game:
  balls_per_game: 1
